services:
  # üóÑÔ∏è Banco de dados do Gateway (Autentica√ß√£o)
  mysql-gateway:
    image: mysql:8.0
    container_name: mysql-gateway
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dud@00747
      MYSQL_DATABASE: gatewaydb
    ports:
      - "3309:3306"
    volumes:
      - gateway_data:/var/lib/mysql
    networks:
      - ecommerce-net

  # üóÑÔ∏è Banco de dados da API de Estoques
  mysql-estoque:
    image: mysql:8.0
    container_name: mysql-estoque
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dud@00747
      MYSQL_DATABASE: estoquedb
    ports:
      - "3307:3306"
    volumes:
      - estoque_data:/var/lib/mysql
    networks:
      - ecommerce-net

  # üóÑÔ∏è Banco de dados da API de Vendas
  mysql-vendas:
    image: mysql:8.0
    container_name: mysql-vendas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dud@00747
      MYSQL_DATABASE: vendasdb
    ports:
      - "3308:3306"
    volumes:
      - vendas_data:/var/lib/mysql
    networks:
      - ecommerce-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  gateway_data:
  estoque_data:
  vendas_data:

networks:
  ecommerce-net:
    driver: bridge
